[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyMPM"
version = "0.0.1"
dependencies = ["numpy >= 1.26.4, < 2.0",
                "scipy >= 1.15.2",
                ]
